server.port=8082

spring.application.name=l1-shipment-service

# Public key (same as L2) for local JWT validation
auth.jwt.public-key=\
-----BEGIN PUBLIC KEY-----\
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuFfk1iKWS711xc3xvgPg\
kHfzP0TioI14KcWAUwsc4NehyuIt1oLEq351ZVXp88ZQN6DYUwB95LFgTLR7KHGf\
aSeSYbFGTFjGUiLODpGitaDmD6kKTDyir8ai2PUkodcy13EFzFR9MzOCITrzcgkl\
W+A8XZ4IKUh5MedcHFo6qx78WH5kjecCIfO2t9GEPj0mFshjNg+g+sm4A4sgx1x7\
pXcq6n8s5n1Qi8iUB7GjIN9abtEuCV4WPgt+CNYuEaTBtPMqS3drIeN+gAROXIhV\
biCH0F/jT+5MPG2qD9xa9RgixJP+s6K3ziKjDLh6qFV+xm/t3cO7JNoZIxuB0HAR\
2wIDAQAB\
-----END PUBLIC KEY-----
auth.jwt.expected-issuer=l2-auth-application-service
auth.jwt.clock-skew-seconds=30

# L2 base URL for revocation checks
l2.base-url=http://localhost:8081

logging.level.com.company.shipmentsvc=DEBUG
