-- ============================================================
-- Oracle DB setup script for L2 Auth Application Service
-- Run this ONCE manually against your Oracle database.
-- Usage: sqlplus authuser/authpass@//localhost:1521/FREEPDB1 @init-oracle.sql
-- ============================================================

-- Drop tables in reverse dependency order (idempotent)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE auth_token_audit CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE auth_api_scope_mapping CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE auth_client_scope CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE auth_scope CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE auth_client CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- ============================================================
-- TABLES
-- ============================================================

CREATE TABLE auth_client (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id VARCHAR2(100) NOT NULL UNIQUE,
    client_name VARCHAR2(255) NOT NULL,
    client_secret_hash VARCHAR2(500) NOT NULL,
    status VARCHAR2(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE auth_scope (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_name VARCHAR2(100) NOT NULL UNIQUE,
    description VARCHAR2(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE auth_client_scope (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id VARCHAR2(100) NOT NULL,
    scope_name VARCHAR2(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (client_id, scope_name)
);

CREATE TABLE auth_api_scope_mapping (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    http_method VARCHAR2(20) NOT NULL,
    api_pattern VARCHAR2(255) NOT NULL,
    required_scope VARCHAR2(100) NOT NULL,
    status VARCHAR2(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE auth_token_audit (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id VARCHAR2(100) NOT NULL,
    token_id VARCHAR2(100),
    event_type VARCHAR2(50) NOT NULL,
    ip_address VARCHAR2(100),
    user_agent VARCHAR2(500),
    status VARCHAR2(30),
    failure_reason VARCHAR2(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- SEED DATA (5 scopes + 1 client)
-- ============================================================

INSERT ALL
    INTO auth_scope (scope_name, description) VALUES ('tracking:read', 'View tracking information')
    INTO auth_scope (scope_name, description) VALUES ('shipment:create', 'Create new shipments')
    INTO auth_scope (scope_name, description) VALUES ('shipment:update', 'Update existing shipments')
    INTO auth_scope (scope_name, description) VALUES ('status:update', 'Update status information')
    INTO auth_scope (scope_name, description) VALUES ('invoice:read', 'View invoices')
SELECT * FROM dual
/

INSERT INTO auth_client (client_id, client_name, client_secret_hash, status)
VALUES ('external_partner_001', 'External Partner 1',
        'actt0d1shqO9VQGDy/LJKg==:XS+XDeVWLYGY5W7IqhLFcKqYCw/mcYJd1pbfj4wDRTM=',
        'ACTIVE')
/

INSERT ALL
    INTO auth_client_scope (client_id, scope_name) VALUES ('external_partner_001', 'tracking:read')
    INTO auth_client_scope (client_id, scope_name) VALUES ('external_partner_001', 'shipment:create')
SELECT * FROM dual
/

COMMIT
/

-- Verify
SELECT table_name FROM user_tables ORDER BY table_name;
SELECT 'Scopes: ' || COUNT(*) FROM auth_scope;
SELECT 'Client: ' || client_id FROM auth_client;
